version: '3.8'
services:
  application:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=bolaget
      - DB_USER=bolaget
      - DB_PASSWORD=bolaget
    depends_on: 
      - database
  database:
    image: linuxserver/mariadb
    container_name: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=bolaget
      - MYSQL_DATABASE=bolaget
      - MYSQL_USER=bolaget
      - MYSQL_PASSWORD=bolaget
    restart: unless-stopped
